# Generated by Django 5.1.4 on 2025-03-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_seller_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AlterField(
            model_name='seller',
            name='slug',
            field=models.SlugField(),
        ),
    ]
